version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force && mix local.rebar --force
      - run: mix do deps.get, deps.compile
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix test
