version: 2
jobs:
  build:
    docker:
      - image: holoshare/holoshare_api
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
      - image: postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      steps:
        - checkout
        - run: mix test
